// Roland Frances

#pragma once

#include "CoreMinimal.h"
#include "Character/SummonCharacter.h"
#include "DemonicSoul.generated.h"

class UHaunt;
struct FDamageEffectParams;

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FRespawnTimerStartSignature);

/**
 * 
 */
UCLASS()
class AURA_API ADemonicSoul : public ASummonCharacter
{
	GENERATED_BODY()
	
public:
	/* Combat Interface */
	virtual void Die(const FVector& DeathImpulse) override;
	/* end Combat Interface */	

protected:
	void OnRespawnTimerEnd();
	void CreateExplosionOnRevival();
	FDamageEffectParams MakeReviveExplosionDamageEffectParams();

	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	float RespawnTimer = 20.f;

	UPROPERTY(BlueprintAssignable)
	FRespawnTimerStartSignature RespawnTimerStartDelegate; // Start the respawn countdown timer for the Demonic Soul's Summon Frame Widget

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades")
	float HellforgedReconstitutionRespawnTimer = 3.f;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|LesserDemonSpawn")
	int32 NumDemonsSpawned = 2;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|LesserDemonSpawn")
	float LesserDemonSpawnDistance = 100.f;

	/*
	* Need to make our own damage effect params for the explosion generated by the Hellforged Reconstitution upgrade since this isn't a gameplay ability class
	*/

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	TSubclassOf<UGameplayEffect> ReviveExplosionDamageEffectClass;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	float ExplosionBaseDamage = 100.f;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	float DeathImpulseMagnitude = 10000.f;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	float KnockbackMagnitude = 2000.f;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	float KnockbackPitch = 45.f;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	float RadialDamageInnerRadius = 250.f;

	UPROPERTY(EditDefaultsOnly, Category = "Upgrades|ReviveExplosion")
	float RadialDamageOuterRadius = 500.f;

private:
	FVector LineTraceStart = FVector(150.f, 0.f, 500.f); // The line trace for finding the ground location to spawn the Demonic Soul on revival
	FVector LineTraceEnd = FVector(150.f, 0.f, -500.f);
	float SpawnLocationZOffset = 88.f; // To prevent the Demonic Soul from spawning inside the ground when respawning at the Vessel's location
	float SpawnSpread = 180.f; // Degrees of spread for the Lesser Demons spawned by the Friends in Low Places upgrade, centered on the forward vector of the Demonic Soul
};
